name: CI
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']
    name: Tests - PHP ${{ matrix.php }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
      - name: Report PHP version
        run: php -v
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-composer-
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest
      - name: check dependancy
        uses: symfonycorp/security-checker-action@v2
      - name: Check quality code
        run: bin/php-cs-fixer fix --ansi --dry-run --using-cache=no --verbose
      - name: Execute phpstan
        run: bin/phpstan
      - name: Execute tests
        run: bin/phpunit --verbose
